# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\85216\Desktop\Friend_Host\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import threading
from PyQt5 import QtCore, QtGui, QtWidgets
from view.chatroom_pyqt import Ui_Chatroom
from view.signup_pyqt import Ui_SignUp

PORT = 9533
#ip = '10.0.0.89'
ip = '167.99.160.18'
#ip = 'localhost'


class Ui_Login(object):
    
    def __init__(self, MainWindow):
        #super(Ui_Login, self).__init__()
        #self.app = QtWidgets.QApplication(sys.argv)
        #self.MainWindow = QtWidgets.QMainWindow()
        #self.ui = Ui_Login()
        #self.ui.setupUi(self.MainWindow)
        self.ADDR = (ip,PORT)
        self.MainWindow = MainWindow
        self.MainWindow.show()
        


    def loginAccount(self):
        threading.Thread(target = self.openChatroom).start()
    
    def openChatroom(self):
        self.name = self.username_entry.text()
        self.ui = Ui_Chatroom(self.app,self.name, self.ADDR)
        #self.chatroom = Ui_Chatroom( self.name, self.ADDR)
        self.MainWindow.close()

    
    def openSignup(self):
        self.signupWindow = QtWidgets.QMainWindow()
        self.ui = Ui_SignUp()
        self.ui.setupUi(self.signupWindow)
        self.signupWindow.show()

    
    
    def setupUi(self, app,MainWindow):
        self.app = app
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(315, 137)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        
        self.gridLayout.setObjectName("gridLayout")
        self.username_label = QtWidgets.QLabel(self.centralwidget)
        self.username_label.setObjectName("label")
        self.gridLayout.addWidget(self.username_label, 0, 0, 1, 1)
        
        self.username_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.username_entry.setObjectName("lineEdit")
        self.username_entry.returnPressed.connect(self.openChatroom)
        self.gridLayout.addWidget(self.username_entry, 0, 1, 1, 1)
        
        self.password_label = QtWidgets.QLabel(self.centralwidget)
        self.password_label.setObjectName("label_2")
        self.gridLayout.addWidget(self.password_label, 1, 0, 1, 1)
        
        self.password_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.password_entry.setObjectName("lineEdit_2")
        self.password_entry.returnPressed.connect(self.openChatroom)
        self.password_entry.setEchoMode(self.password_entry.Password)
        self.gridLayout.addWidget(self.password_entry, 1, 1, 1, 1)
        
        self.login_Button = QtWidgets.QPushButton(self.centralwidget)
        self.login_Button.setObjectName("login_Button")
        self.login_Button.clicked.connect(self.openChatroom)
        self.gridLayout.addWidget(self.login_Button, 2, 1, 1, 1)
        
        self.signup_Button = QtWidgets.QPushButton(self.centralwidget)
        self.signup_Button.setObjectName("signup_Button")
        self.signup_Button.clicked.connect(self.openSignup)
        self.gridLayout.addWidget(self.signup_Button, 2, 0, 1, 1)
        
        
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.username_label.setText(_translate("MainWindow", "Username"))
        self.password_label.setText(_translate("MainWindow", "Password"))
        self.login_Button.setText(_translate("MainWindow", "Login"))
        self.signup_Button.setText(_translate("MainWindow", "Sign Up"))







