# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SignUp(object):
    def setupUi(self, SignUp):
        SignUp.setObjectName("SignUp")
        SignUp.resize(376, 210)
        self.centralwidget = QtWidgets.QWidget(SignUp)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.signup_password_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.signup_password_entry.setObjectName("signup_password_entry")
        
        self.gridLayout.addWidget(self.signup_password_entry, 2, 1, 1, 2)
        self.signup_name = QtWidgets.QLabel(self.centralwidget)
        self.signup_name.setObjectName("signup_name")
        
        self.gridLayout.addWidget(self.signup_name, 1, 0, 1, 1)
        self.signup_code = QtWidgets.QLabel(self.centralwidget)
        self.signup_code.setObjectName("signup_code")
        
        self.gridLayout.addWidget(self.signup_code, 0, 0, 1, 1)
        self.signup_btn = QtWidgets.QPushButton(self.centralwidget)
        self.signup_btn.setObjectName("signup_btn")
        
        self.gridLayout.addWidget(self.signup_btn, 3, 2, 1, 1)
        self.signup_password = QtWidgets.QLabel(self.centralwidget)
        self.signup_password.setObjectName("signup_password")
        
        self.gridLayout.addWidget(self.signup_password, 2, 0, 1, 1)
        self.code_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.code_entry.setObjectName("code_entry")
        
        self.gridLayout.addWidget(self.code_entry, 0, 1, 1, 2)
        self.signup_username_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.signup_username_entry.setObjectName("signup_username_entry")
        
        self.gridLayout.addWidget(self.signup_username_entry, 1, 1, 1, 2)
        self.signup_back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.signup_back_btn.setObjectName("signup_back_btn")
        self.gridLayout.addWidget(self.signup_back_btn, 3, 0, 1, 1)
        SignUp.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SignUp)
        self.statusbar.setObjectName("statusbar")
        SignUp.setStatusBar(self.statusbar)

        self.retranslateUi(SignUp)
        QtCore.QMetaObject.connectSlotsByName(SignUp)

    def retranslateUi(self, SignUp):
        _translate = QtCore.QCoreApplication.translate
        SignUp.setWindowTitle(_translate("SignUp", "Sign Up"))
        self.signup_name.setText(_translate("SignUp", "Username"))
        self.signup_code.setText(_translate("SignUp", "Invite Code"))
        self.signup_btn.setText(_translate("SignUp", "Sign Up"))
        self.signup_password.setText(_translate("SignUp", "Password"))
        self.signup_back_btn.setText(_translate("SignUp", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SignUp = QtWidgets.QMainWindow()
    ui = Ui_SignUp()
    ui.setupUi(SignUp)
    SignUp.show()
    sys.exit(app.exec_())
